project_id = "lynkvfduzqdyvlzgriyh"

[functions.google-sheets-sync]
verify_jwt = false

[functions.maps-directions]
verify_jwt = false

[functions.gcs-upload]
verify_jwt = false

[functions.vision-ocr]
verify_jwt = false
