project_id = "lynkvfduzqdyvlzgriyh"

[functions.google-sheets-sync]
verify_jwt = false

[functions.maps-directions]
verify_jwt = false

[functions.gcs-upload]
verify_jwt = false

[functions.gcs-proxy]
verify_jwt = false

[functions.vision-ocr]
verify_jwt = false

[functions.postcode-lookup]
verify_jwt = false

[functions.business-search]
verify_jwt = false

[functions.place-details]
verify_jwt = false

[functions.vehicle-lookup]
verify_jwt = false

[functions.gcs-fix-acl]
verify_jwt = false
